---
title: "About me"
---

# Alex Hirtle, Ualberta Finance Honours \| Student

Alex Hirtle is a fourth year Finance Honours student studying at the University of Alberta School of Business.

Before enrolling in University, Alex started a small business importing cars from Japan. Through his experiences building a customer base, dealing with the export, import, customs, and accounting process he honed his skills in CRM, logistics, budgeting, marketing, and sales. Throughout his studies, Alex continues to import a number of vehicles, doing most of the work from the seat of his motorcycle while travelling across B.C. and Alberta during his summer break.

Additionally, Alex has worked on academic research papers with professors from UCLA, U of A, SFU, and Cambridge. He provided quantitative reports, data cleaning and procurement, and industry reports for researchers to further use in their publishing.

Alex has become well known among other finance students and practitioners around the university as a hardworking, reliable, out of the box thinker who isn't afraid to learn something new.
